### PR TITLE
Fixes #81

### LINKED ISSUE #81: Access denied stops walking file tree
Hi

When walking a folder using Files.walkFileTree if a file / folder cannot be accessed an exception is thrown and the whole walking is finished.

It might be good to handle such cases by overriding visitFileFailed and continue instead of breaking

### PR DESCRIPTION
**Pull request by zenios**
I decided its better to expose the whole file visiting functionality to the consumer providing a default implementation that uses Files.walkFileTree and continues on visitFileFailed. You can override using a new visitor or keep using the default passing an error handler.

The default files visitor error handler does not allow you to override the default response (CONTINUE) since we require consistent behaviour.

Looking forwards to your comments

### CODE REVIEW

File: core/src/main/java/io/methvin/watcher/visitor/DefaultFilesVisitor.java [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+
+          @Override
+          public FileVisitResult visitFile(Path file, BasicFileAttributes attrs)
+              throws IOException {
+            onFile.call(file);
+            return FileVisitResult.CONTINUE;
+          }
+
+          @Override
+          public FileVisitResult visitFileFailed(Path file, IOException exc) throws IOException {
```
Comment (gmethvin) [inline core/src/main/java/io/methvin/watcher/visitor/DefaultFilesVisitor.java:37]: Do we also need to do the same thing for `postVisitDirectory`? I think that will get called with the exception in case there's an exception iterating over the directory that wasn't related to a specific file.

**Review by gmethvin — COMMENTED** [review]
The approach overall seems good.

As far as testing it, you could make `onFile` and/or `onDirectory` explicitly throw an `IOException` for some files, and make sure it still sees the rest of the files in the directory tree.

File: core/src/main/java/io/methvin/watcher/visitor/DefaultFilesVisitor.java [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+    this.failedCallback = failedCallback;
+  }
+
+  private final FailedCallback failedCallback;
+
+  @Override
+  public void recursiveVisitFiles(Path file, Callback onDirectory, Callback onFile)
+      throws IOException {
+    SimpleFileVisitor<Path> visitor =
+        new SimpleFileVisitor<>() {
```
Comment (gmethvin) [inline core/src/main/java/io/methvin/watcher/visitor/DefaultFilesVisitor.java:21]: we're building this for jdk8 so this doesn't work :(

```
[error] /Users/runner/work/directory-watcher/directory-watcher/core/src/main/java/io/methvin/watcher/visitor/DefaultFilesVisitor.java:21:1: cannot infer type arguments for java.nio.file.SimpleFileVisitor<T>
[error]   reason: '<>' with anonymous inner classes is not supported in -source 8
[error]     (use -source 9 or higher to enable '<>' with anonymous inner classes)
[error] SimpleFileVisitor<>
```

Hopefully we'll be able to drop jdk8 support in the next year or so, but at the moment directory-watcher is being used by other libraries that still need to support it.

**Comment by zenios** [comment]
Hi i did the changes requested. Please check

File: core/src/main/java/io/methvin/watcher/visitor/FileTreeVisitor.java [hunk 3]
```diff
@@ -0,0 +1,17 @@
+package io.methvin.watcher.visitor;
+
+import java.io.IOException;
+
+import java.nio.file.Path;
+
+public interface FileTreeVisitor {
+
+  /** The default file tree visitor instance, which uses Files.walkFileTree. */
+  FileTreeVisitor DEFAULT_FILES_VISITOR = new DefaultFileTreeVisitor();
```
Comment (gmethvin) [inline core/src/main/java/io/methvin/watcher/visitor/FileTreeVisitor.java:10]: should rename to `DEFAULT_FILE_TREE_VISITOR`

File: core/src/main/java/io/methvin/watcher/PathUtils.java [hunk 4]
```diff
@@ -42,17 +43,17 @@ public static <T> SortedMap<Path, T> subMap(SortedMap<Path, T> pathMap, Path tre
...
-  public static SortedMap<Path, FileHash> createHashCodeMap(List<Path> files, FileHasher fileHasher)
-      throws IOException {
+  public static SortedMap<Path, FileHash> createHashCodeMap(
+      List<Path> files, FileHasher fileHasher, FileTreeVisitor fileTreeVisitor) throws IOException {
     SortedMap<Path, FileHash> lastModifiedMap = new ConcurrentSkipListMap<>();
     if (fileHasher != null) {
       for (Path file : files) {
-        for (Path child : recursiveListFiles(file)) {
+        for (Path child : recursiveListFiles(fileTreeVisitor, file)) {
           FileHash hash = PathUtils.hash(fileHasher, child);
```
Comment (gmethvin) [inline core/src/main/java/io/methvin/watcher/PathUtils.java:57]: So I think now errors are handled differently in `createHashCodeMap` than in `initWatcherState`. Since `initWatcherState` calls `PathUtils.hash` inside the `Callback`, an exception during hashing would be caught by `onFailure`. In `createHashCodeMap` we're using the visitor to just get a list of the files and doing the hashing outside the callback, so an exception would not be caught.

The main difference here is that `createHashCodeMap` is used by `MacOSXListeningWatchService` whereas `initWatcherState` is used by `DirectoryWatcher` directly, but they basically do the same thing so it probably makes sense to have consistent behavior.

**Review by gmethvin — COMMENTED** [review]
The code looks pretty good, but I noticed we might not be catching exceptions in `createHashCodeMap`, as I commented below.

For testing, I think it's sufficient to just test the behavior of `createHashCodeMap` and `initWatcherState`. You could simulate a failure by having a hasher implementation that throws an exception for some files.

**Comment by zenios** [comment]
Hi

createHashCodeMap and initWatcherState now behave the same. i.e Hashing done inside the callback

File: core/src/main/java/io/methvin/watcher/PathUtils.java [hunk 5]
```diff
@@ -42,40 +43,36 @@ public static <T> SortedMap<Path, T> subMap(SortedMap<Path, T> pathMap, Path tre
...
-  public static SortedMap<Path, FileHash> createHashCodeMap(Path file, FileHasher fileHasher)
-      throws IOException {
-    return createHashCodeMap(Collections.singletonList(file), fileHasher);
-  }
-
-  public static SortedMap<Path, FileHash> createHashCodeMap(List<Path> files, FileHasher fileHasher)
-      throws IOException {
+  public static SortedMap<Path, FileHash> createHashCodeMap(
+      Path file, FileHasher fileHasher, FileTreeVisitor fileTreeVisitor) throws IOException {
     SortedMap<Path, FileHash> lastModifiedMap = new ConcurrentSkipListMap<>();
```
Comment (gmethvin) [inline core/src/main/java/io/methvin/watcher/PathUtils.java:48]: maybe while you're at it you can change this map to be called `hashes` instead of `lastModifiedMap`. I think the name is wrong because previously this used the last modified time of the file rather than the hash.

**Review by gmethvin — COMMENTED** [review]
Looks good. There are a few test failures in `ChangeSetTest` but I think those are just flaky tests.

I'm fine with merging this as soon as you've added tests. It would also be nice to update the README explaining the new feature and default behavior with respect to errors.

**Comment by zenios** [comment]
Hi 
Throwing an IOException from visitFile callback will not cause visitFileFailed to be called. visitFileFailed in only called if file attributes could not be read prior to calling visitFile. In order to enforce this in my tests i had to create a directory and setExecutable(false, false) to it, which i am not sure if it works on Windows. I am testing it on linux and everything seems fine.

Check it out and let me know

**Comment by zenios** [comment]
It seems that setExecutable does not work on WIndows. Disabled the test

**Review by gmethvin — APPROVED** [review]

**Comment by gmethvin** [comment]
released in v0.16.0
