### PR TITLE
Handle overflow properly on macOS watcher

### LINKED ISSUE #5: IllegalStateException: Queue full
this is on a rather big multiproject sbt build

```
JNA: Callback io.methvin.watchservice.MacOSXListeningWatchService$MacOSXListeningCallback@4778113f threw the following exception:
java.lang.IllegalStateException: Queue full
	at java.util.AbstractQueue.add(AbstractQueue.java:98)
	at java.util.concurrent.ArrayBlockingQueue.add(ArrayBlockingQueue.java:312)
	at io.methvin.watchservice.AbstractWatchKey.signalEvent(AbstractWatchKey.java:156)
	at io.methvin.watchservice.MacOSXListeningWatchService$MacOSXListeningCallback.invoke(MacOSXListeningWatchService.java:171)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:485)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:515)
	at com.sun.jna.Native.invokeVoid(Native Method)
	at com.sun.jna.Function.invoke(Function.java:374)
	at com.sun.jna.Function.invoke(Function.java:323)
	at com.sun.jna.Library$Handler.invoke(Library.java:236)
	at com.sun.proxy.$Proxy11.CFRunLoopRun(Unknown Source)
	at io.methvin.watchservice.MacOSXListeningWatchService$CFRunLoopThread.run(MacOSXListeningWatchService.java:105)
```

### PR DESCRIPTION
**Pull request by gmethvin**
If we get too many events we should signal the overflow event. 

This also increases the default queue size to 1024 and adds a system property `io.methvin.watchService.queueSize` to customize the queue size.

Fixes #5.

### CODE REVIEW

File: core/src/main/java/io/methvin/watchservice/AbstractWatchKey.java [hunk 1]
```diff
@@ -41,7 +41,9 @@
  */
 class AbstractWatchKey implements WatchKey {
 
-  static final int MAX_QUEUE_SIZE = 256;
+  static final int DEFAULT_QUEUE_SIZE = 1024;
+  static final int QUEUE_SIZE = Integer.parseInt(System.getProperty(
```
Comment (gmethvin) [inline core/src/main/java/io/methvin/watchservice/AbstractWatchKey.java]: Note: I removed the system property in favor of explicit configuration. See #7.
